version: '3'
services:
  weather-service:
    image: "weather-service-img"
    container_name: "weather-service"
    ports:
      - "8080:8080"
  prometheus:
    image: "prometheus-img"
    container_name: "prometheus"
    ports:
      - "9090:9090"
  grafana:
    image: "grafana-img"
    container_name: "grafana"
    ports:
      - "80:3000"

