FROM grafana/grafana:8.3.0



ADD /grafana/grafana.ini /etc/grafana/grafana.ini
ADD /grafana/provisioning/datasource.yml /etc/grafana/provisioning/datasources/
ADD /grafana/provisioning/dashboards/ /etc/grafana/provisioning/dashboards/

