FROM grafana/grafana:8.3.0



ADD /grafana/grafana.ini /etc/grafana/grafana.ini
ADD /grafana/provisioning/datasource.yml /etc/grafana/provisioning/datasources
ADD /grafana/provisioning/dashboard.yml /etc/grafana/provisioning/dashboards
