FROM ubuntu:20.04

# Install OpenJDK-11

RUN apt update && apt upgrade -y

RUN apt-cache search openjdk

RUN apt-get install openjdk-17-jdk -y

RUN apt-get clean

ADD /weather /home/weatherapi

RUN chmod -R 755 /home/weatherapi

RUN sed -i -e 's/\r$//' /home/weatherapi/gradlew

RUN /home/weatherapi/gradlew build -p /home/weatherapi

CMD java -jar /home/weatherapi/build/libs/weather-0.0.1.jar
